config/routes.rb
Rails.application.routes.draw do
  # resources :appearances
  # resources :players
  get "/users/challenger/:id", to: "users#challenger", as: "challenger"
  resources :teams
  resources :games
  post "/teams/:id", to: "team#update"
  root "application#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/login", to: "sessions#destroy"
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
end

app/models/appearance.rb
class Appearance < ApplicationRecord
  belongs_to :player_team
  belongs_to :game
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :appearances
  has_many :player_teams, through: :appearances
  has_many :teams, through: :player_teams
  has_many :players, through: :player_teams

  def total_points_by_team(team_id)
    sql = <<-SQL
    SELECT SUM(appearances.points)
    FROM games
    JOIN appearances on games.id = appearances.game_id
    JOIN player_teams on appearances.player_team_id = player_teams.id
    JOIN teams on player_teams.team_id = teams.id
    WHERE teams.id = #{team_id} AND games.id = #{self.id}
    SQL

    ActiveRecord::Base.connection.execute(sql)[0][0]
  end

  def simulate_game(player_teams)
    player_teams.each do |pt|
      Appearance.create(
        player_team: pt,
        game: self,
        points: rand(7..25),
        rebounds: rand(0..12),
        assists: rand(0..12),
        steals: rand(1..4),
        blocks: rand(1..4),
      )
    end
    update_team_record
  end

  def update_team_record
    teams = self.teams.uniq
    team_one = teams[0]
    team_two = teams[1]
    team_one_pts = self.total_points_by_team(team_one.id)
    team_two_pts = self.total_points_by_team(team_two.id)
    if team_one_pts > team_two_pts
      team_one.wins +=1
      team_two.losses +=1
    elsif team_two_pts > team_one_pts
      team_two.wins +=1
      team_one.losses +=1
    end
    team_one.save
    team_two.save
  end

  def game_appearances_by_team(team_id)
    sql = <<-SQL
    SELECT appearances.*, players.name as player_name
    FROM games
    JOIN appearances on games.id = appearances.game_id
    JOIN player_teams on appearances.player_team_id = player_teams.id
    JOIN players on player_teams.id = players.id
    JOIN teams on player_teams.team_id = teams.id
    WHERE teams.id = ? AND games.id = ?
    SQL

    Appearance.find_by_sql([sql, team_id, self.id])
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :player_teams
  has_many :teams, through: :player_teams
  has_many :appearances, through: :player_teams
  
end

app/models/player_team.rb
class PlayerTeam < ApplicationRecord
  belongs_to :player
  belongs_to :team
  has_many :appearances
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  has_many :player_teams
  has_many :players, through: :player_teams
  has_many :appearances, through: :player_teams
  has_many :games, through: :appearances
  validate :has_exactly_five_players
  validates :name, presence: true, uniqueness: true, length: { maximum: 35 }

  def has_exactly_five_players
    if self.players.length != 5
      errors.add(:team_size, "A team must have five players.")
    end
  end

  def win_percentage
    wins + losses == 0 ? 0.00 : (wins.to_f / (wins + losses)).round(2)
  end

  def self.top_five_teams
    sql = <<-SQL
    SELECT (CAST(wins AS float) / (CAST(wins AS float) + CAST(losses AS float))) AS win_pct, name
    FROM teams
    ORDER BY win_pct DESC
    LIMIT 5
    SQL

    ActiveRecord::Base.connection.execute(sql)
    # returns array of hashes with key 0 being win_pct and 1 as team name
  end

  def self.names
    sql = <<-SQL
    SELECT teams.name
    FROM teams
    SQL

    ActiveRecord::Base.connection.execute(sql).map { |x| x["name"]}
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :teams
  has_many :player_teams, through: :teams
  has_many :players, through: :player_teams
  has_many :appearances, through: :player_teams
  has_many :games, through: :appearances

  has_secure_password
  validates :name, :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def home
  end

  def logged_in?
    redirect_to root_path if !session[:user_id]
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :logged_in?

  def create
    if params[:team][:home_id] && params[:team][:away_id]
      @game = Game.new(date: Time.now)
      @home_team = Team.find_by(id: params[:team][:home_id])
      @away_team = Team.find_by(id: params[:team][:away_id])
      @game.simulate_game(@home_team.player_teams + @away_team.player_teams)
      @game.save
      redirect_to @game
    else
      redirect_to user_path(session[:user_id])
    end
  end

  def show
    @game = Game.find_by_id(params[:id])
    @home_team = @game.teams.uniq[0]
    @away_team = @game.teams.uniq[1]
    @home_appearances = @game.game_appearances_by_team(@home_team.id)
    @away_appearances = @game.game_appearances_by_team(@away_team.id)
  end

  def index
    @games = Game.last(9)
    @leaderboard = Team.top_five_teams
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :login
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @error = true
      flash.now[:danger] = 'Invalid email/password combination'
      render :login
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  before_action :logged_in?

  def new
    @players = Player.all
    if User.find_by_id(session[:user_id]).teams.any?
      redirect_to user_path(session[:user_id])
    end
    @team = Team.new
    @team_player_ids = []
  end

  def create
    @team = Team.new(team_params)
    @team.user_id = session[:user_id]
    if @team.save
      redirect_to user_path(session[:user_id])
    else
      flash[:message] = 'Enter a team name and select five players.'
      redirect_to new_team_path
    end
  end

  def edit
    @players = Player.all
    @team = Team.includes(:players).find_by_id(params[:id])
    @team_player_ids = @team.player_ids
  end

  def update
    @team = Team.find_by_id(params[:id])
    if @team.update(team_params)
      redirect_to user_path(session[:user_id])
    else
      @players = Player.all
      @team_player_ids = @team.player_ids
      flash.now[:message] = 'Enter a team name and select five players.'
      render 'edit'
    end
  end

  private

  def team_params
    params.require(:team).permit(
      :name,
      player_ids: []
      )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_team_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @team = @user.teams
    if @team.empty?
      redirect_to new_team_path
    end
    @playable_teams = Team.all - @team
  end

  def challenger
    @user = User.find_by_id(params[:id])
    @team = @user.teams.first
    render layout: false
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/appearances_helper.rb
module AppearancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<style media="screen">
  @keyframes spin {
    0% {
      transform: rotate(0deg);
    }
    49% {
      transform: rotate(360deg);
    }
    50% {
      transform: translateY(0px) scale(1);
    }
    100% {
      transform: translateY(400px) scale(0.3);
    }
  }

  #basketball {
    animation: spin 3s linear infinite;
  }

  .basket {
    z-index: 2;
  }

  .basketball-container {
    padding: 30px;
    width: 400px;
    margin: 0 auto;
  }

  img {
    position: relative;
  }
</style>

<div class="basketball-container">
  <center>
    <%= image_tag asset_path('basketball.png'), id: "basketball", size: "250" %>
  </center>
  <center style="z-index: 10;">
    <%= image_tag asset_path('basketball-basket.png'), class: "basket", size: "300x217" %>
  </center>
</div>

app/views/games/_player_results.html.erb
<tr>
  <td class="player"><%= appearance.player_team.player.name %></td>
  <td class="number"><%= appearance.points %></td>
  <td class="number"><%= appearance.rebounds %></td>
  <td class="number"><%= appearance.assists %></td>
  <td class="number"><%= appearance.steals %></td>
  <td class="number"><%= appearance.blocks %></td>
</tr>

app/views/games/index.html.erb
<div class="container">
  <table class="game-results" style="margin: 40px auto;">
    <tr>
      <th class="player"> Team</th>
      <th>Win Percentage</th>
    </tr>
    <% @leaderboard.each do |win_pct_hash| %>
    <tr>
      <td><%= win_pct_hash[1] %></td>
      <td class="number"><%= win_pct_hash[0] ? win_pct_hash[0].round(2) : 0 %></td>
    </tr>
    <% end %>
  </table>
</div>

<div class="container">
  <% @games.each do |game| %>
    <a href="<%= game_path(game) %>">
      <div class="game-scorecard">
        <center>
          <div class="team-score">
            <div class="team" ><%= game.teams.uniq.first.name[0,15]%></div>
            <div class="score"><%= game.total_points_by_team(game.teams.uniq.first.id) %></div>
          </div>
          <div class="team-score">
            <div class="team" ><%= game.teams.uniq.last.name[0,15]%></div>
            <div class="score" ><%= game.total_points_by_team(game.teams.uniq.last.id) %></div>
          </div>
          <div class="date" ><%= game.date.strftime('%B %C, %G') %></div>
        </center>
      </div>
    </a>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="team-results-container">
  <center>
  <h1> Game Statistics:</h1>

  <div class="team-results">
    <h2>Home Team</h2>
    <h3><%= @home_team.name %></h3>
    <h2>Final Score:<%= " #{@game.total_points_by_team(@home_team.id)}" %></h2>
    <table class="game-results">
      <tr>
        <th class="player">Player</th>
        <th>Points</th>
        <th>Assists</th>
        <th>Rebounds</th>
        <th>Steals</th>
        <th>Blocks</th>
      </tr>
      <%= render partial: "player_results", collection: @home_appearances, as: :appearance %>
    </table>
  </div>

  <div class="team-results">
    <h2>Away Team</h2>
    <h3><%= @away_team.name %></h3>
    <h2>Final Score:<%= " #{@game.total_points_by_team(@away_team.id)}" %></h2>
    <table class="game-results">
      <tr>
        <th class="player">Player</th>
        <th>Points</th>
        <th>Assists</th>
        <th>Rebounds</th>
        <th>Steals</th>
        <th>Blocks</th>
      </tr>
      <%= render partial: "player_results", collection: @away_appearances, as: :appearance %>
    </table>
  </div>
  </center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatironBasketballAssociation</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="nav-bar">
    <div class="nav-bar-logo">
      <div class="nav-bar-logo-text">
        Flatiron Basketball
      </div>
    </div>
      <% if !session[:user_id] %>
        <%= link_to signup_path do %>
          <div class="nav-bar-button">
            <div class="nav-bar-button-text">
              SIGNUP
            </div>
          </div>
        <% end %>
        <%= link_to login_path do %>
        <div class="nav-bar-button">
          <div class="nav-bar-button-text">
            LOGIN
          </div>
        </div>
        <% end %>
      <% else %>
        <%= link_to login_path, method: :delete do %>
        <div class="nav-bar-button">
          <div class="nav-bar-button-text">
            LOGOUT
          </div>
        </div>
        <% end %>
        <%= link_to user_path(session[:user_id]) do %>
        <div class="nav-bar-button">
          <div class="nav-bar-button-text">
            MY TEAM
          </div>
        </div>
        <% end %>
        <%= link_to games_path do %>
        <div class="nav-bar-button">
          <div class="nav-bar-button-text">
            STANDINGS
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="nav-bar-space">
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/challenger.html.erb
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<style media="screen">
  div.card {
    height: 176;
    border-color: grey !important;
  }

  .card-container {
    border-color: grey;
  }

  .card-title {
    background-color: grey;
    border-color: grey;
  }

  td, th, tr {
    border-color: grey !important;
  }
</style>

<% @user.players.each_with_index do |player, index| %>
  <div class="card-container">
    <input type="checkbox" class="hidden" id="<%= "player-#{index}" %>" name="team[player_ids][]" value="<%= player.id %>" checked>
    <div class="card">
      <div class="card-content">
        <div class="card-title-container">
          <div class="card-title"><%= player.name %></div>
        </div>
        <table class="card-table">
          <tr>
            <td>PPG</td>
            <td><%= player.ppg %></td>
          </tr>
          <tr>
            <td>APG</td>
            <td><%= player.apg %></td>
          </tr>
          <tr>
            <td>RPG</td>
            <td><%= player.rpg %></td>
          </tr>
          <tr>
            <td>SPG</td>
            <td><%= player.spg %></td>
          </tr>
          <tr>
            <td class="last">BPG</td>
            <td class="last"><%= player.bpg %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
<% end %>

</body>

app/views/users/new.html.erb
<div class="form-container">
  <h1>Join Flatiron Basketball</h1>
  <%= form_for(@user, url: signup_path) do |f| %>

  <%= f.text_field :name, placeholder: "Name", class: "form-field #{'error' if @user.errors.include?('name')}" %>
  <%= f.email_field :email, placeholder: "Email", class: "form-field #{'error' if @user.errors.include?('email')}" %>
  <%= f.password_field :password, placeholder: "Password", class: "form-field #{'error' if @user.errors.include?('password')}" %>


  <input type="submit" name="Signup" value="Signup" class="form-button" id="<%= 'error-button' if @user.errors.any? %>">
  <% end %>
  <p> Already have an account? Please <%= link_to "sign in", login_path%><p>
</div>

app/views/users/show.html.erb
<style media="screen">
  @keyframes spin {
  0% { transform: rotate(0deg);}
  100% { transform: rotate(360deg);}
  }

  .basketball-container {
    position: relative;
    top: 10px;
    margin-left: 20px;
  }

  #basketball {
    animation: spin 2s linear infinite;
  }
</style>

  <div class="container">
    <div class="team-form-container" style="margin-top: 20px;">
      <h2 style="display: inline-block; margin-bottom: 0;"><%= @user.teams.first.name%></h2>
      <%= link_to edit_team_path(@user.teams.first) do %>
        <div class="edit-team-button" style="margin-left: 10px;">
          <div class="edit-team-button-text-container">
            <div class="edit-team-button-text">
              Edit
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% @user.players.each_with_index do |player, index| %>
      <div class="card-container">
        <input type="checkbox" class="hidden" id="<%= "player-#{index}" %>" name="team[player_ids][]" value="<%= player.id %>" checked>
        <div class="card">
          <div class="card-content">
            <div class="card-title-container">
              <div class="card-title"><%= player.name %></div>
            </div>
            <table class="card-table">
              <tr>
                <td>PPG</td>
                <td><%= player.ppg %></td>
              </tr>
              <tr>
                <td>APG</td>
                <td><%= player.apg %></td>
              </tr>
              <tr>
                <td>RPG</td>
                <td><%= player.rpg %></td>
              </tr>
              <tr>
                <td>SPG</td>
                <td><%= player.spg %></td>
              </tr>
              <tr>
                <td class="last">BPG</td>
                <td class="last"><%= player.bpg %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    <% end %>

<style media="screen">
label.drop-down-option a {
  color: grey;
  font-size: 10pt;
}

label.drop-down-option {
  display: inline-block;
  padding: 5px 10px;
  background-color: white;
  border: solid thin grey;
  border-radius: 20px;
  color: grey;
}

.challenger-selector {
  overflow-y: hidden;
  overflow-x: scroll;
  max-height: 50px;
  margin: 20px 0 0 0;
  white-space: nowrap;
  width: 700px;
  display: inline-block;
  vertical-align: top;
  padding: 10px;
}

.challenger-selector input[type=radio] {
  opacity: 0;
  position: absolute;
  left: 5px;
}

.horizontal {
  display: inline;
}

.challenger-selector input[type=radio]:checked + label {
  background-color: grey;
  color: white;
}

.borderless-button {
  display: inline-block;
  margin: 30px 0 0 0;
}
</style>

  <div class="team-form-container">
    <%= form_tag games_path do %>
      <%= hidden_field_tag "team[home_id]", @user.teams.first.id %>

      <div class="challenger-selector" >
        <% @playable_teams.each do |team| %>
        <div class="horizontal">
          <input type="radio" class="hidden" id="<%= "team-#{team.id}" %>" name="team[away_id]" value="<%= team.id %>">
          <label for="<%= "team-#{team.id}" %>" class="drop-down-option">
            <%= team.name %>
            <a href="<%= challenger_path(team) %>" target="challenger_iframe">&#128270;</a>
          </label>
        </div>
        <% end %>
      </div>

      <%= button_tag type: "submit", class: "borderless-button" do %>
        <div class="edit-team-button" style="margin-left: 10px; width: 125px;">
          <div class="edit-team-button-text-container">
            <div class="edit-team-button-text">
              Challenge
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="container">
  <iframe name="challenger_iframe" src="" style="border:none;" width="925" height="210"></iframe>
</div>